-- EGG ISLE v5 · EggLang (ModuleScript → ReplicatedStorage)
-- i18n: EN หลัก + TH ES PT ID VI ZH KO JA · ตรวจจับภาษาอัตโนมัติ
local LS = game:GetService("LocalizationService")
local M = {}

M.PET_R = { cat = "common", dog = "common", rab = "common", pan = "uncommon", cap = "uncommon", ele = "rare", lio = "rare", dra = "epic", uni = "epic", gld = "legendary", phx = "legendary" }
M.WEIGHT = { common = 10, uncommon = 20, rare = 40, epic = 80, legendary = 150, mythic = 300, secret = 600, divine = 1200, mystery = 2500, trash = 0.01 }
M.PWR = { cat = 1, dog = 1, rab = 1, pan = 3, cap = 3, ele = 10, lio = 10, dra = 40, uni = 40, gld = 200, phx = 200, bull = 1000, scor = 1000, bear = 1000, bat = 1000, sheep = 5000, sphinx = 5000, wraith = 5000, shd = 5000, seraph = 25000, void = 100000, sloth = 1000 }
M.PET_N = {
	en = { cat = "Orange Cat", dog = "Corgi", rab = "White Bunny", pan = "Panda", cap = "Capybara", ele = "Pink Elephant", lio = "Golden Lion", dra = "Ice Dragon", uni = "Rainbow Unicorn", gld = "Golden Dragon", phx = "Cosmic Phoenix", bull = "Golden Bull", scor = "Pharaoh Scorpion", bear = "Emperor Polar Bear", bat = "Blood Bat", sheep = "Cloud Sheep", sphinx = "Sphinx", wraith = "Ice Wraith", shd = "Shadow Dragon", seraph = "Light Seraph", void = "The Void Walker", sloth = "Trash Sloth" },
	th = { cat = "แมวส้ม", dog = "คอร์กี้", rab = "กระต่ายขาว", pan = "แพนด้า", cap = "คาปิบาร่า", ele = "ช้างชมพู", lio = "สิงโตทอง", dra = "มังกรน้ำแข็ง", uni = "ยูนิคอร์นรุ้ง", gld = "ดราก้อนทอง", phx = "ฟีนิกซ์จักรวาล", bull = "วัวทอง", scor = "แมงป่องฟาโรห์", bear = "จักรพรรดิหมีขาว", bat = "ค้างคาวโลหิต", sheep = "แกะเมฆา", sphinx = "สฟิงซ์", wraith = "วิญญาณน้ำแข็ง", shd = "มังกรเงา", seraph = "เซราฟิมแสง", void = "ผู้ย่างเท้าแห่งความว่างเปล่า", sloth = "สลอธกาก" },
}
M.RAR = {
	en = { common = "Common", uncommon = "Uncommon", rare = "Rare", epic = "Epic", legendary = "Legendary", mythic = "Mythic", secret = "Secret", divine = "Divine", mystery = "???", trash = "Trash" },
	th = { common = "ธรรมดา", uncommon = "ไม่ธรรมดา", rare = "หายาก", epic = "มหากาพย์", legendary = "ตำนาน", mythic = "เทพเจ้า", secret = "ลับสุดยอด", divine = "ศักดิ์สิทธิ์", mystery = "???", trash = "กาก" },
	es = { common = "Común", uncommon = "Infrecuente", rare = "Raro", epic = "Épico", legendary = "Legendario", mythic = "Mítico", secret = "Secreto", divine = "Divino", mystery = "???", trash = "Basura" },
	pt = { common = "Comum", uncommon = "Incomum", rare = "Raro", epic = "Épico", legendary = "Lendário", mythic = "Mítico", secret = "Secreto", divine = "Divino", mystery = "???", trash = "Lixo" },
	id = { common = "Biasa", uncommon = "Tak Umum", rare = "Langka", epic = "Epik", legendary = "Legendaris", mythic = "Mitos", secret = "Rahasia", divine = "Ilahi", mystery = "???", trash = "Sampah" },
	vi = { common = "Thường", uncommon = "Hiếm Vừa", rare = "Hiếm", epic = "Sử Thi", legendary = "Huyền Thoại", mythic = "Thần Thoại", secret = "Bí Mật", divine = "Thần Thánh", mystery = "???", trash = "Rác" },
	zh = { common = "普通", uncommon = "进阶", rare = "稀有", epic = "史诗", legendary = "传说", mythic = "神话", secret = "隐藏", divine = "神圣", mystery = "???", trash = "垃圾" },
	ko = { common = "일반", uncommon = "고급", rare = "희귀", epic = "영웅", legendary = "전설", mythic = "신화", secret = "비밀", divine = "신성", mystery = "???", trash = "쓰레기" },
	ja = { common = "ノーマル", uncommon = "アンコモン", rare = "レア", epic = "エピック", legendary = "伝説", mythic = "神話", secret = "シークレット", divine = "神聖", mystery = "???", trash = "トラッシュ" },
}

M.L = {
	en = {
		day = "DAY", night = "NIGHT", carry = "Carrying egg {1} kg - walk {2}", holdbtn = "HOLD\nTO GRAB",
		admin = "ADMIN", announce = "ANNOUNCEMENT", skip = "Skip",
		m_boat = "BOAT", m_garden = "GARDEN", m_index = "INDEX", m_fuse = "FUSE", m_trail = "TRAIL", m_chest = "CHEST", m_bag = "BAG", m_lang = "LANG",
		t_boat = "My Boat", t_garden = "My Garden", t_index = "Island Index", t_fuse = "Fusion Machine", t_trail = "Trail Shop", t_chest = "Free Chest", t_bag = "Pet Bag", t_lang = "Language",
		board_btn = "Board boat (stand near a boat)", leave_btn = "Leave boat", upboat = "Upgrade boat", upgarden = "Upgrade garden",
		fuse_btn = "FUSE", sell = "Sell", open_chest = "Open chest (+$750 / 20h)", chest_wait = "Chest ready in {1}h",
		fuse_info = "Fuse 3 same pets = BIG form, power x2", stick = "[stick unlocked]",
		boat_spd = "Current boat speed x{1}", slots = "Slots {1} · species {2}",
		bag_info = "In bag (not earning): {1}", active = "Active {1}/{2}",
		b_income = "MOST $/SEC", b_robux = "MOST ROBUX SPENT", b_play = "LONGEST PLAY (HRS)",
		gift_ok = "Chest opened! +$750", hatch = "Hatched {1} [{2}]!", pickup = "Holding {1} kg egg - back to your garden!",
		night_now = "Night! Eggs hidden on the islands - sail out!", dawn = "Morning! Eggs reset in 20s",
		legend = "A LEGENDARY egg appeared on island 5!", idx_done = "Island {1} index complete! Stick unlocked",
		boat_up = "Boat upgraded! speed x{1}", garden_up = "Garden upgraded! slots {1}",
		trail_on = "{1} equipped - walk x{2}", fuse_ok = "Fused! {1} is now BIG (x2)",
		sold = "Sold {1} +${2}", big = "BIG",
		full_boat = "Boat maxed!", full_garden = "Garden maxed!",
		trail1 = "Green Wind Trail", trail2 = "Ice Trail", trail3 = "Fire Trail",
		money_add = "+${1} added", allpets = "All 11 pets granted", reset_ok = "Save reset",
		egg_summon = "{1} summoned {2} ({3} kg) - race to grab it!", robux_thx = "Thanks! +${1} added",
		intro1 = "After a long journey... the Egg Sea lies ahead",
		intro2 = "!? The water shakes... something huge is below us",
		intro3 = "The Guardian of the Shadow Isle!! It remembers intruders!",
		intro4 = "BOOM!! The ship breaks apart-",
		intro5 = "Blub... blub... (everything fades to black)", intro6 = "",
		welcome = "Welcome to Egg Isle! Tonight... sail out for your first egg",
		guard_name = "Guardian {1}", guard_hit = "The guardian snatched your egg back to its nest!",
		tut_title = "HOW TO PLAY", tut1 = "1. At NIGHT eggs appear - board a boat at the dock and sail to an island",
		tut2 = "2. Walk to an egg and HOLD 3s to grab it (heavier = slower but earns more)",
		tut3 = "3. Place the egg in your garden and wait - rarer & heavier = longer (max 2 days), then HATCH",
		tut4 = "4. Try the menus: FUSE 3 same pets, TRAIL shop, free CHEST, LANG button",
		tut_skip = "Skip", tut_end = "Finish",
		placed = "Egg placed! Hatching in ~{1} min", place_egg = "Place egg (start hatch timer)", hatch_now = "HATCH NOW!",
		incub = "Hatching: {1} ({2})", ready = "READY", dup_convert = "Already owned - converted +${1}",
		reveal = "??? REVEALED: {1}!", mystery_egg = "A ??? egg appeared somewhere...", hint = "Hint: {1}", unknown = "???",
	},
	th = {
		day = "กลางวัน", night = "กลางคืน", carry = "ถือไข่ {1} กก. - เดิน {2}", holdbtn = "กดค้าง\nเก็บไข่",
		admin = "ผู้ดูแล", announce = "ประกาศ", skip = "ข้าม",
		m_boat = "เรือ", m_garden = "สวน", m_index = "ดัชนี", m_fuse = "ฟิวส์", m_trail = "เทรล", m_chest = "หีบ", m_bag = "กระเป๋า", m_lang = "ภาษา",
		t_boat = "เรือของฉัน", t_garden = "สวนของฉัน", t_index = "ดัชนีเกาะ", t_fuse = "เครื่องฟิวส์", t_trail = "ร้านเทรล", t_chest = "หีบฟรี", t_bag = "กระเป๋าเพ็ท", t_lang = "ภาษา",
		board_btn = "ขึ้นเรือ (ยืนใกล้เรือ)", leave_btn = "ลงเรือ", upboat = "อัปเรือ", upgarden = "อัปสวน",
		fuse_btn = "ฟิวส์", sell = "ขาย", open_chest = "เปิดหีบ (+$750 / 20 ชม.)", chest_wait = "หีบพร้อมใน {1} ชม.",
		fuse_info = "ฟิวส์สัตว์เดียวกัน 3 ตัว = ร่างยักษ์ พลัง x2", stick = "[ปลดล็อกไม้]",
		boat_spd = "ความเร็วเรือปัจจุบัน x{1}", slots = "ช่อง {1} · ชนิด {2}",
		bag_info = "ในกระเป๋า (ไม่ผลิต): {1}", active = "ใช้งาน {1}/{2}",
		b_income = "เงิน/วิ มากสุด", b_robux = "จ่ายโรบัคมากสุด", b_play = "เล่นนานสุด (ชม.)",
		gift_ok = "เปิดหีบ! +$750", hatch = "ฟักได้ {1} [{2}]", pickup = "ถือไข่ {1} กก. - กลับสวนของคุณ!",
		night_now = "กลางคืนแล้ว! ไข่ซ่อนตามเกาะ ออกเรือเลย!", dawn = "เช้าแล้ว! รีไข่ใน 20 วิ",
		legend = "ไข่ตำนานโผล่ที่เกาะ 5!", idx_done = "ดัชนีเกาะ {1} ครบ! ปลดล็อกไม้",
		boat_up = "อัปเรือ! ความเร็ว x{1}", garden_up = "อัปสวน! ช่อง {1}",
		trail_on = "สวม {1} - เดิน x{2}", fuse_ok = "ฟิวส์สำเร็จ! {1} กลายเป็นยักษ์ (x2)",
		sold = "ขาย {1} +${2}", big = "ยักษ์",
		full_boat = "เรือเต็มขั้น!", full_garden = "สวนเต็มขั้น!",
		trail1 = "เทรลลมเขียว", trail2 = "เทรลน้ำแข็ง", trail3 = "เทรลเพลิง",
		money_add = "เติม ${1}", allpets = "แจกครบ 11 ชนิด", reset_ok = "รีเซ็ตเซฟ",
		egg_summon = "{1} เสกไข่ {2} ({3} กก.) - แย่งกัน!", robux_thx = "ขอบคุณ! +${1}",
		intro1 = "หลังการเดินทางอันยาวนาน... ทะเลแห่งเกาะไข่อยู่ตรงหน้า",
		intro2 = "!? ผิวน้ำสั่นแรงขึ้น... มีบางอย่างใหญ่โตอยู่ใต้เรา",
		intro3 = "ผู้พิทักษ์แห่งเกาะอเวจี!! มันจำหน้าผู้บุกรุกได้!",
		intro4 = "ตู้ม!! เรือแตกแล้ว-",
		intro5 = "ตุ๊บ... ตุ๊บ... (ทุกอย่างมืดลง)", intro6 = "",
		welcome = "ยินดีต้อนรับสู่ Egg Isle! คืนนี้... ออกเรือไปหาไข่ใบแรก",
		guard_name = "ผู้พิทักษ์ {1}", guard_hit = "ผู้พิทักษ์แย่งไข่คืนรังไปแล้ว!",
		tut_title = "วิธีเล่น", tut1 = "1. กลางคืนไข่จะโผล่ - ขึ้นเรือที่ท่านแล่นไปเกาะ",
		tut2 = "2. เดินใกล้ไข่แล้วกดค้าง 3 วิเพื่อเก็บ (หนัก=ช้าแต่เงินเยอะ)",
		tut3 = "3. วางไข่ที่สวนแล้วรอเวลาฟัก (หายาก/หนัก = รอนาน สูงสุด 2 วัน) แล้วค่อยกดฟัก",
		tut4 = "4. ลองเมนู: ฟิวส์สัตว์เดียวกัน 3 ตัว, ร้านเทรล, หีบฟรี, ปุ่มภาษา",
		tut_skip = "ข้าม", tut_end = "จบการสอน",
		placed = "วางไข่แล้ว! ฟักใน ~{1} นาที", place_egg = "วางไข่ (เริ่มนับเวลาฟัก)", hatch_now = "ฟักเลย!",
		incub = "กำลังฟัก: {1} ({2})", ready = "พร้อมฟัก", dup_convert = "มีอยู่แล้ว - แปลงเป็น +${1}",
		reveal = "??? ถูกเปิดเผย: {1}!", mystery_egg = "ไข่ ??? โผล่ที่ไหนสักแห่ง...", hint = "ใบ้: {1}", unknown = "???",
	},
	es = {
		day = "DÍA", night = "NOCHE", carry = "Llevas huevo de {1} kg - paso {2}", holdbtn = "MANTEN\nPARA TOMAR",
		admin = "ADMIN", announce = "ANUNCIO", skip = "Saltar",
		m_boat = "BARCO", m_garden = "JARDÍN", m_index = "ÍNDICE", m_fuse = "FUSIÓN", m_trail = "ESTELA", m_chest = "COFRE", m_bag = "BOLSA", m_lang = "IDIOMA",
		t_boat = "Mi Barco", t_garden = "Mi Jardín", t_index = "Índice de Islas", t_fuse = "Máquina de Fusión", t_trail = "Tienda de Estelas", t_chest = "Cofre Gratis", t_bag = "Bolsa de Mascotas", t_lang = "Idioma",
		board_btn = "Subir al barco", leave_btn = "Bajar", upboat = "Mejorar barco", upgarden = "Mejorar jardín",
		fuse_btn = "FUSIONAR", sell = "Vender", open_chest = "Abrir cofre (+$750 / 20h)", chest_wait = "Cofre listo en {1}h",
		fuse_info = "Fusiona 3 mascotas iguales = forma GIGANTE, poder x2", stick = "[palo desbloqueado]",
		boat_spd = "Velocidad de barco x{1}", slots = "Espacios {1} · especies {2}",
		bag_info = "En bolsa (sin producir): {1}", active = "Activas {1}/{2}",
		b_income = "MÁS $/SEG", b_robux = "MÁS ROBUX GASTADO", b_play = "MÁS TIEMPO (HRS)",
		gift_ok = "Cofre abierto! +$750", hatch = "Nació {1} [{2}]!", pickup = "Sostienes huevo de {1} kg - vuelve a tu jardín!",
		night_now = "Noche! Huevos ocultos en las islas - zarpa!", dawn = "Mañana! Huevos se reinician en 20s",
		legend = "Un huevo LEGENDARIO en la isla 5!", idx_done = "Índice de isla {1} completo!",
		boat_up = "Barco mejorado! x{1}", garden_up = "Jardín mejorado! espacios {1}",
		trail_on = "{1} equipada - paso x{2}", fuse_ok = "Fusionado! {1} ahora es GIGANTE (x2)",
		sold = "Vendiste {1} +${2}", big = "GIGANTE",
		full_boat = "Barco al máximo!", full_garden = "Jardín al máximo!",
		trail1 = "Estela Verde", trail2 = "Estela de Hielo", trail3 = "Estela de Fuego",
		money_add = "+${1} añadido", allpets = "11 mascotas dadas", reset_ok = "Guardado reiniciado",
		egg_summon = "{1} invocó {2} ({3} kg) - carrera por tomarlo!", robux_thx = "Gracias! +${1}",
		intro1 = "Tras un largo viaje... el Mar de Huevos está frente a nosotros",
		intro2 = "!? El agua tiembla... algo enorme está abajo",
		intro3 = "El Guardián de la Isla Sombra!! Recuerda a los intrusos!",
		intro4 = "BOOM!! El barco se rompe-",
		intro5 = "Glub... glub... (todo se oscurece)", intro6 = "",
		welcome = "Bienvenido a Egg Isle! Esta noche... zarpa por tu primer huevo",
		guard_name = "Guardián {1}", guard_hit = "El guardián recuperó el huevo!",
		tut_title = "CÓMO JUGAR", tut1 = "1. De NOCHE aparecen huevos - sube al barco y zarpa",
		tut2 = "2. Acércate y MANTEN 3s (más pesado = más lento pero gana más)",
		tut3 = "3. Coloca el huevo en tu jardin y espera para eclosionar",
		tut4 = "4. Prueba: FUSIÓN, estelas, cofre gratis, idioma",
		tut_skip = "Saltar", tut_end = "Listo",
		placed = "Huevo colocado! ~{1} min", place_egg = "Colocar huevo", hatch_now = "ECLOSIONAR!",
		incub = "Eclosionando: {1} ({2})", ready = "LISTO", dup_convert = "Ya lo tienes +${1}",
		reveal = "??? REVELADO: {1}!", mystery_egg = "Un huevo ??? aparecio...", hint = "Pista: {1}", unknown = "???",
	},
	pt = {
		day = "DIA", night = "NOITE", carry = "Carregando ovo de {1} kg - passo {2}", holdbtn = "SEGURE\nPARA PEGAR",
		admin = "ADMIN", announce = "ANÚNCIO", skip = "Pular",
		m_boat = "BARCO", m_garden = "JARDIM", m_index = "ÍNDICE", m_fuse = "FUSÃO", m_trail = "RASTRO", m_chest = "BAÚ", m_bag = "BOLSA", m_lang = "IDIOMA",
		t_boat = "Meu Barco", t_garden = "Meu Jardim", t_index = "Índice das Ilhas", t_fuse = "Máquina de Fusão", t_trail = "Loja de Rastros", t_chest = "Baú Grátis", t_bag = "Bolsa de Pets", t_lang = "Idioma",
		board_btn = "Entrar no barco", leave_btn = "Sair do barco", upboat = "Melhorar barco", upgarden = "Melhorar jardim",
		fuse_btn = "FUNDIR", sell = "Vender", open_chest = "Abrir baú (+$750 / 20h)", chest_wait = "Baú pronto em {1}h",
		fuse_info = "Funda 3 pets iguais = forma GIGANTE, poder x2", stick = "[vara desbloqueada]",
		boat_spd = "Velocidade do barco x{1}", slots = "Vagas {1} · espécies {2}",
		bag_info = "Na bolsa (sem render): {1}", active = "Ativos {1}/{2}",
		b_income = "MAIS $/SEG", b_robux = "MAIS ROBUX GASTO", b_play = "MAIS TEMPO (HRS)",
		gift_ok = "Baú aberto! +$750", hatch = "Nasceu {1} [{2}]!", pickup = "Segurando ovo de {1} kg - volte ao jardim!",
		night_now = "Noite! Ovos escondidos nas ilhas - zarpe!", dawn = "Manhã! Ovos reiniciam em 20s",
		legend = "Um ovo LENDÁRIO na ilha 5!", idx_done = "Índice da ilha {1} completo!",
		boat_up = "Barco melhorado! x{1}", garden_up = "Jardim melhorado! vagas {1}",
		trail_on = "{1} equipado - passo x{2}", fuse_ok = "Fundido! {1} agora é GIGANTE (x2)",
		sold = "Vendeu {1} +${2}", big = "GIGANTE",
		full_boat = "Barco no máximo!", full_garden = "Jardim no máximo!",
		trail1 = "Rastro Verde", trail2 = "Rastro de Gelo", trail3 = "Rastro de Fogo",
		money_add = "+${1} adicionado", allpets = "11 pets dados", reset_ok = "Save reiniciado",
		egg_summon = "{1} invocou {2} ({3} kg) - corra para pegar!", robux_thx = "Obrigado! +${1}",
		intro1 = "Após uma longa viagem... o Mar dos Ovos está à frente",
		intro2 = "!? A água treme... algo enorme está embaixo",
		intro3 = "O Guardião da Ilha Sombra!! Ele lembra dos invasores!",
		intro4 = "BOOM!! O navio se parte-",
		intro5 = "Blub... blub... (tudo escurece)", intro6 = "",
		welcome = "Bem-vindo à Egg Isle! Esta noite... zarpe pelo seu primeiro ovo",
		guard_name = "Guardião {1}", guard_hit = "O guardião levou o ovo de volta!",
		tut_title = "COMO JOGAR", tut1 = "1. À NOITE ovos aparecem - entre no barco e zarpe",
		tut2 = "2. Chegue perto e SEGURE 3s (mais pesado = mais lento, rende mais)",
		tut3 = "3. Coloque o ovo no jardim e espere para chocar",
		tut4 = "4. Explore: FUSÃO, rastros, baú grátis, idioma",
		tut_skip = "Pular", tut_end = "Concluir",
		placed = "Ovo colocado! ~{1} min", place_egg = "Colocar ovo", hatch_now = "CHOCHAR!",
		incub = "Chocando: {1} ({2})", ready = "PRONTO", dup_convert = "Ja tem +${1}",
		reveal = "??? REVELADO: {1}!", mystery_egg = "Um ovo ??? apareceu...", hint = "Dica: {1}", unknown = "???",
	},
	id = {
		day = "SIANG", night = "MALAM", carry = "Membawa telur {1} kg - jalan {2}", holdbtn = "TAHAN\nUNTUK AMBIL",
		admin = "ADMIN", announce = "PENGUMUMAN", skip = "Lewati",
		m_boat = "PERAHU", m_garden = "KEBUN", m_index = "INDEKS", m_fuse = "FUSI", m_trail = "JEJAK", m_chest = "PETI", m_bag = "TAS", m_lang = "BAHASA",
		t_boat = "Perahuku", t_garden = "Kebunku", t_index = "Indeks Pulau", t_fuse = "Mesin Fusi", t_trail = "Toko Jejak", t_chest = "Peti Gratis", t_bag = "Tas Hewan", t_lang = "Bahasa",
		board_btn = "Naik perahu", leave_btn = "Turun", upboat = "Tingkatkan perahu", upgarden = "Tingkatkan kebun",
		fuse_btn = "FUSI", sell = "Jual", open_chest = "Buka peti (+$750 / 20j)", chest_wait = "Peti siap dalam {1}j",
		fuse_info = "Fusi 3 hewan sama = bentuk BESAR, daya x2", stick = "[tongkat terbuka]",
		boat_spd = "Kecepatan perahu x{1}", slots = "Slot {1} · spesies {2}",
		bag_info = "Di tas (tidak menghasilkan): {1}", active = "Aktif {1}/{2}",
		b_income = "$/DETIK TERTINGGI", b_robux = "ROBUX TERBANYAK", b_play = "MAIN TERLAMA (JAM)",
		gift_ok = "Peti dibuka! +$750", hatch = "Menetas {1} [{2}]!", pickup = "Membawa telur {1} kg - kembali ke kebunmu!",
		night_now = "Malam! Telur tersembunyi di pulau - berlayar!", dawn = "Pagi! Telur reset dalam 20s",
		legend = "Telur LEGENDARIS muncul di pulau 5!", idx_done = "Indeks pulau {1} lengkap!",
		boat_up = "Perahu ditingkatkan! x{1}", garden_up = "Kebun ditingkatkan! slot {1}",
		trail_on = "{1} dipakai - jalan x{2}", fuse_ok = "Fusi berhasil! {1} kini BESAR (x2)",
		sold = "Menjual {1} +${2}", big = "BESAR",
		full_boat = "Perahu maksimal!", full_garden = "Kebun maksimal!",
		trail1 = "Jejak Hijau", trail2 = "Jejak Es", trail3 = "Jejak Api",
		money_add = "+${1} ditambah", allpets = "11 hewan diberikan", reset_ok = "Save direset",
		egg_summon = "{1} memunculkan {2} ({3} kg) - rebutan!", robux_thx = "Terima kasih! +${1}",
		intro1 = "Setelah perjalanan panjang... Laut Telur terbentang",
		intro2 = "!? Air bergetar... sesuatu yang besar di bawah",
		intro3 = "Penjaga Pulau Bayangan!! Ia ingat penyusup!",
		intro4 = "BOOM!! Kapal hancur-",
		intro5 = "Blub... blub... (semua gelap)", intro6 = "",
		welcome = "Selamat datang di Egg Isle! Malam ini... berlayarlah mencari telur pertamamu",
		guard_name = "Penjaga {1}", guard_hit = "Penjaga merebut kembali telurnya!",
		tut_title = "CARA MAIN", tut1 = "1. MALAM hari telur muncul - naik perahu dan berlayar",
		tut2 = "2. Dekati telur dan TAHAN 3s (berat = lambat tapi hasil besar)",
		tut3 = "3. Letakkan telur di kebunmu dan tunggu untuk menetas",
		tut4 = "4. Coba menu: FUSI, jejak, peti gratis, bahasa",
		tut_skip = "Lewati", tut_end = "Selesai",
		placed = "Telur diletakkan! ~{1} mnt", place_egg = "Letakkan telur", hatch_now = "TETASKAN!",
		incub = "Menetas: {1} ({2})", ready = "SIAP", dup_convert = "Sudah punya +${1}",
		reveal = "??? TERUNGKAP: {1}!", mystery_egg = "Telur ??? muncul...", hint = "Petunjuk: {1}", unknown = "???",
	},
	vi = {
		day = "NGÀY", night = "ĐÊM", carry = "Đang ôm trứng {1} kg - đi {2}", holdbtn = "GIỮ\nĐỂ NHẶT",
		admin = "ADMIN", announce = "THÔNG BÁO", skip = "Bỏ qua",
		m_boat = "THUYỀN", m_garden = "VƯỜN", m_index = "CHỈ MỤC", m_fuse = "HỢP NHẤT", m_trail = "VẾT", m_chest = "RƯƠNG", m_bag = "TÚI", m_lang = "NGÔN NGỮ",
		t_boat = "Thuyền của tôi", t_garden = "Vườn của tôi", t_index = "Chỉ mục đảo", t_fuse = "Máy hợp nhất", t_trail = "Cửa hàng vết", t_chest = "Rương miễn phí", t_bag = "Túi thú", t_lang = "Ngôn ngữ",
		board_btn = "Lên thuyền", leave_btn = "Xuống thuyền", upboat = "Nâng cấp thuyền", upgarden = "Nâng cấp vườn",
		fuse_btn = "HỢP NHẤT", sell = "Bán", open_chest = "Mở rương (+$750 / 20h)", chest_wait = "Rương sẵn sàng sau {1}h",
		fuse_info = "Hợp nhất 3 thú giống nhau = dạng KHỔNG LỒ, sức x2", stick = "[mở khóa gậy]",
		boat_spd = "Tốc độ thuyền x{1}", slots = "Ô {1} · loài {2}",
		bag_info = "Trong túi (không sinh lợi): {1}", active = "Hoạt động {1}/{2}",
		b_income = "NHIỀU $/GIÂY NHẤT", b_robux = "CHI NHIỀU ROBUX NHẤT", b_play = "CHƠI LÂU NHẤT (GIỜ)",
		gift_ok = "Đã mở rương! +$750", hatch = "Nở ra {1} [{2}]!", pickup = "Đang ôm trứng {1} kg - về vườn của bạn!",
		night_now = "Đêm rồi! Trứng ẩn trên đảo - ra khơi!", dawn = "Sáng rồi! Trứng reset sau 20s",
		legend = "Trứng HUYỀN THOẠI xuất hiện ở đảo 5!", idx_done = "Hoàn thành chỉ mục đảo {1}!",
		boat_up = "Thuyền nâng cấp! x{1}", garden_up = "Vườn nâng cấp! ô {1}",
		trail_on = "Trang bị {1} - đi x{2}", fuse_ok = "Đã hợp nhất! {1} thành KHỔNG LỒ (x2)",
		sold = "Đã bán {1} +${2}", big = "KHỔNG LỒ",
		full_boat = "Thuyền tối đa!", full_garden = "Vườn tối đa!",
		trail1 = "Vết Gió Xanh", trail2 = "Vết Băng", trail3 = "Vết Lửa",
		money_add = "+${1} đã thêm", allpets = "Đã nhận 11 thú", reset_ok = "Đã reset save",
		egg_summon = "{1} triệu hồi {2} ({3} kg) - tranh nhau nhặt!", robux_thx = "Cảm ơn! +${1}",
		intro1 = "Sau hành trình dài... Biển Trứng hiện ra trước mặt",
		intro2 = "!? Mặt nước rung chuyển... thứ gì đó khổng lồ bên dưới",
		intro3 = "Hộ Vệ của Đảo Bóng Đêm!! Nó nhớ kẻ xâm nhập!",
		intro4 = "BOOM!! Thuyền vỡ tan-",
		intro5 = "Ục... ục... (mọi thứ tối sầm)", intro6 = "",
		welcome = "Chào mừng đến Egg Isle! Đêm nay... ra khơi tìm quả trứng đầu tiên",
		guard_name = "Hộ Vệ {1}", guard_hit = "Hộ Vệ đã đoạt lại trứng!",
		tut_title = "CÁCH CHƠI", tut1 = "1. Ban ĐÊM trứng xuất hiện - lên thuyền ra khơi",
		tut2 = "2. Lại gần và GIỮ 3s (nặng = chậm nhưng thu nhiều hơn)",
		tut3 = "3. Đặt trứng vào vườn và chờ nở",
		tut4 = "4. Thử menu: HỢP NHẤT, vết, rương miễn phí, ngôn ngữ",
		tut_skip = "Bỏ qua", tut_end = "Xong",
		placed = "Đã đặt trứng! ~{1} phút", place_egg = "Đặt trứng", hatch_now = "NỞ NGAY!",
		incub = "Đang nở: {1} ({2})", ready = "SẴN SÀNG", dup_convert = "Đã sở hữu +${1}",
		reveal = "??? LỘ DIỆN: {1}!", mystery_egg = "Một quả ??? xuất hiện...", hint = "Gợi ý: {1}", unknown = "???",
	},
	zh = {
		day = "白天", night = "夜晚", carry = "抱着 {1} kg 蛋 - 移速 {2}", holdbtn = "长按\n拾取",
		admin = "管理员", announce = "公告", skip = "跳过",
		m_boat = "船", m_garden = "花园", m_index = "图鉴", m_fuse = "融合", m_trail = "拖尾", m_chest = "宝箱", m_bag = "背包", m_lang = "语言",
		t_boat = "我的船", t_garden = "我的花园", t_index = "岛屿图鉴", t_fuse = "融合机", t_trail = "拖尾商店", t_chest = "免费宝箱", t_bag = "宠物背包", t_lang = "语言",
		board_btn = "上船", leave_btn = "下船", upboat = "升级船", upgarden = "升级花园",
		fuse_btn = "融合", sell = "出售", open_chest = "开宝箱 (+$750 / 20小时)", chest_wait = "宝箱 {1} 小时后可开",
		fuse_info = "3 只相同宠物融合 = 巨型形态, 力量 x2", stick = "[已解锁木杖]",
		boat_spd = "当前船速 x{1}", slots = "栏位 {1} · 种类 {2}",
		bag_info = "背包中 (不产出): {1}", active = "生效 {1}/{2}",
		b_income = "最高 $/秒", b_robux = "最多 ROBUX 消费", b_play = "最长游玩 (小时)",
		gift_ok = "宝箱已开! +$750", hatch = "孵出 {1} [{2}]!", pickup = "抱着 {1} kg 蛋 - 回你的花园!",
		night_now = "夜晚! 蛋藏在各岛 - 出发!", dawn = "早晨! 蛋 20 秒后重置",
		legend = "传说蛋出现在 5 号岛!", idx_done = "岛屿 {1} 图鉴完成!",
		boat_up = "船已升级! x{1}", garden_up = "花园已升级! 栏位 {1}",
		trail_on = "已装备 {1} - 移速 x{2}", fuse_ok = "融合成功! {1} 变为巨型 (x2)",
		sold = "出售 {1} +${2}", big = "巨型",
		full_boat = "船已满级!", full_garden = "花园已满级!",
		trail1 = "绿风拖尾", trail2 = "冰霜拖尾", trail3 = "烈焰拖尾",
		money_add = "+${1} 已添加", allpets = "已发放 11 种宠物", reset_ok = "存档已重置",
		egg_summon = "{1} 召唤了 {2} ({3} kg) - 快去抢!", robux_thx = "谢谢! +${1}",
		intro1 = "漫长旅途之后... 蛋之海就在眼前",
		intro2 = "!? 水面在震动... 下面有巨大的东西",
		intro3 = "暗影岛的守护者!! 它记得入侵者!",
		intro4 = "轰!! 船碎了-",
		intro5 = "咕嘟... 咕嘟... (一切变黑)", intro6 = "",
		welcome = "欢迎来到 Egg Isle! 今晚... 出发寻找你的第一颗蛋",
		guard_name = "守护者 {1}", guard_hit = "守护者把蛋夺回巢穴了!",
		tut_title = "玩法教学", tut1 = "1. 夜晚蛋会出现 - 上船出航",
		tut2 = "2. 靠近蛋长按 3 秒 (越重越慢但收益更高)",
		tut3 = "3. 把蛋放在花园等待孵化",
		tut4 = "4. 试试菜单: 融合, 拖尾, 免费宝箱, 语言",
		tut_skip = "跳过", tut_end = "完成",
		placed = "蛋已放置! 约{1}分钟", place_egg = "放置蛋", hatch_now = "立即孵化!",
		incub = "孵化中: {1} ({2})", ready = "完成", dup_convert = "已拥有 +${1}",
		reveal = "??? 揭晓: {1}!", mystery_egg = "??? 蛋出现了...", hint = "提示: {1}", unknown = "???",
	},
	ko = {
		day = "낮", night = "밤", carry = "알 {1} kg 드는 중 - 속도 {2}", holdbtn = "길게\n눌러 줍기",
		admin = "관리자", announce = "공지", skip = "건너뛰기",
		m_boat = "배", m_garden = "정원", m_index = "도감", m_fuse = "퓨전", m_trail = "트레일", m_chest = "상자", m_bag = "가방", m_lang = "언어",
		t_boat = "내 배", t_garden = "내 정원", t_index = "섬 도감", t_fuse = "퓨전 머신", t_trail = "트레일 상점", t_chest = "무료 상자", t_bag = "펫 가방", t_lang = "언어",
		board_btn = "배 타기", leave_btn = "배 내리기", upboat = "배 강화", upgarden = "정원 강화",
		fuse_btn = "퓨전", sell = "판매", open_chest = "상자 열기 (+$750 / 20시간)", chest_wait = "상자 {1}시간 후",
		fuse_info = "같은 펫 3마리 퓨전 = 거대 형태, 능력 x2", stick = "[지팡이 해제]",
		boat_spd = "현재 배 속도 x{1}", slots = "슬롯 {1} · 종류 {2}",
		bag_info = "가방 (수익 없음): {1}", active = "활성 {1}/{2}",
		b_income = "최고 $/초", b_robux = "최다 로벅 소비", b_play = "최장 플레이 (시간)",
		gift_ok = "상자 열림! +$750", hatch = "{1} 부화! [{2}]", pickup = "{1} kg 알 드는 중 - 정원으로!",
		night_now = "밤! 섬에 알이 숨겨짐 - 출항!", dawn = "아침! 20초 후 알 초기화",
		legend = "전설 알이 5섬에 등장!", idx_done = "섬 {1} 도감 완료!",
		boat_up = "배 강화! x{1}", garden_up = "정원 강화! 슬롯 {1}",
		trail_on = "{1} 장착 - 속도 x{2}", fuse_ok = "퓨전 성공! {1} 거대화 (x2)",
		sold = "{1} 판매 +${2}", big = "거대",
		full_boat = "배 최대!", full_garden = "정원 최대!",
		trail1 = "초록 바람 트레일", trail2 = "얼음 트레일", trail3 = "화염 트레일",
		money_add = "+${1} 추가", allpets = "11종 지급", reset_ok = "세이브 초기화",
		egg_summon = "{1} 이(가) {2} ({3} kg) 소환 - 빨리 주우세요!", robux_thx = "감사합니다! +${1}",
		intro1 = "긴 여정 끝... 알의 바다가 눈앞에",
		intro2 = "!? 물이 흔들린다... 거대한 무언가가 아래에",
		intro3 = "그림자 섬의 수호자!! 침입자를 기억한다!",
		intro4 = "콰광!! 배가 부서진다-",
		intro5 = "꿀렁... 꿀렁... (모두 어두워진다)", intro6 = "",
		welcome = "Egg Isle에 오신 것을 환영합니다! 오늘 밤... 첫 알을 찾으러 출항하세요",
		guard_name = "수호자 {1}", guard_hit = "수호자가 알을 되가져갔습니다!",
		tut_title = "플레이 방법", tut1 = "1. 밤이 되면 알 등장 - 보트 타고 출항",
		tut2 = "2. 알에 다가가 3초 길게 눌러 줍기 (무거울수록 느리지만 수익 업)",
		tut3 = "3. 정원에 알을 놓고 기다린 후 부화",
		tut4 = "4. 메뉴 탐색: 퓨전, 트레일, 무료 상자, 언어",
		tut_skip = "건너뛰기", tut_end = "완료",
		placed = "알 배치! 약{1}분", place_egg = "알 놓기", hatch_now = "지금 부화!",
		incub = "부화 중: {1} ({2})", ready = "완료", dup_convert = "이미 보유 +${1}",
		reveal = "??? 공개: {1}!", mystery_egg = "??? 알이 나타났습니다...", hint = "힌트: {1}", unknown = "???",
	},
	ja = {
		day = "昼", night = "夜", carry = "卵 {1} kg 所持 - 歩速 {2}", holdbtn = "長押しで\n拾う",
		admin = "管理人", announce = "お知らせ", skip = "スキップ",
		m_boat = "ボート", m_garden = "庭", m_index = "図鑑", m_fuse = "融合", m_trail = "トレイル", m_chest = "宝箱", m_bag = "バッグ", m_lang = "言語",
		t_boat = "マイボート", t_garden = "マイ庭", t_index = "島図鑑", t_fuse = "融合マシン", t_trail = "トレイルショップ", t_chest = "無料宝箱", t_bag = "ペットバッグ", t_lang = "言語",
		board_btn = "ボートに乗る", leave_btn = "ボートを降りる", upboat = "ボート強化", upgarden = "庭強化",
		fuse_btn = "融合", sell = "売却", open_chest = "宝箱を開く (+$750 / 20h)", chest_wait = "宝箱あと {1}h",
		fuse_info = "同じペット3体を融合 = BIG形態, 力x2", stick = "[杖解放]",
		boat_spd = "現在のボート速度 x{1}", slots = "スロット {1} · 種類 {2}",
		bag_info = "バッグ内 (生産なし): {1}", active = "稼働 {1}/{2}",
		b_income = "最高 $/秒", b_robux = "最多ロバックス消費", b_play = "最長プレイ (時間)",
		gift_ok = "宝箱を開けた! +$750", hatch = "{1} が孵化! [{2}]", pickup = "{1} kg の卵を所持 - 庭へ戻れ!",
		night_now = "夜! 島に卵が隠れた - 出航!", dawn = "朝! 20秒で卵リセット",
		legend = "伝説の卵が島5に出現!", idx_done = "島 {1} の図鑑完成!",
		boat_up = "ボート強化! x{1}", garden_up = "庭強化! スロット {1}",
		trail_on = "{1} 装備 - 歩速 x{2}", fuse_ok = "融合成功! {1} がBIGに (x2)",
		sold = "{1} を売却 +${2}", big = "BIG",
		full_boat = "ボート最大!", full_garden = "庭最大!",
		trail1 = "緑風のトレイル", trail2 = "氷のトレイル", trail3 = "炎のトレイル",
		money_add = "+${1} 追加", allpets = "11種を付与", reset_ok = "セーブ初期化",
		egg_summon = "{1} が {2} ({3} kg) を召喚 - 取りに行け!", robux_thx = "ありがとう! +${1}",
		intro1 = "長い旅の末... 卵の海が目の前に",
		intro2 = "!? 水面が揺れる... 下に巨大な何かが",
		intro3 = "影の島の守護者!! 侵入者を覚えている!",
		intro4 = "ドカーン!! 船が壊れる-",
		intro5 = "ゴボ... ゴボ... (全てが暗転)", intro6 = "",
		welcome = "Egg Isleへようこそ! 今夜... 最初の卵を探しに出航しよう",
		guard_name = "ガーディアン {1}", guard_hit = "ガーディアンに卵を持ち去られた!",
		tut_title = "あそびかた", tut1 = "1. 夜になると卵が出現 - ボートで出航",
		tut2 = "2. 卵に近づき3秒長押しで拾う (重いほど遅いが収入増)",
		tut3 = "3. 庭に卵を置いて孵化完了を待つ",
		tut4 = "4. メニューを試そう: 融合, トレイル, 無料宝箱, 言語",
		tut_skip = "スキップ", tut_end = "完了",
		placed = "卵を設置! 約{1}分", place_egg = "卵を置く", hatch_now = "今すぐ孵化!",
		incub = "孵化中: {1} ({2})", ready = "完了", dup_convert = "所持済み +${1}",
		reveal = "??? 判明: {1}!", mystery_egg = "???の卵が現れた...", hint = "ヒント: {1}", unknown = "???",
	},
}


M.PET_META = {
	cat = { r = "common", isl = 2 }, dog = { r = "common", isl = 2 }, rab = { r = "common", isl = 2 }, pan = { r = "uncommon", isl = 2 },
	cap = { r = "uncommon", isl = 3 }, ele = { r = "rare", isl = 3 }, lio = { r = "rare", isl = 3 },
	dra = { r = "epic", isl = 4 }, uni = { r = "epic", isl = 4 }, gld = { r = "legendary", isl = 5 }, phx = { r = "legendary", isl = 5 },
	bull = { r = "mythic", isl = 2, hint = { en = "A mighty horned beast of the grass fields", th = "สัตว์เขาทรงพลังแห่งทุ่งหญ้า" } },
	scor = { r = "mythic", isl = 3, hint = { en = "A stinging king beneath the desert sands", th = "ราชาเหล็กในใต้ทรายทะเลทราย" } },
	bear = { r = "mythic", isl = 4, hint = { en = "The frozen emperor who sleeps once a year", th = "จักรพรรดิน้ำแข็งที่หลับปีละครั้ง" } },
	bat = { r = "mythic", isl = 5, hint = { en = "Wings of blood in the darkest sky", th = "ปีกสีเลือดในฟ้าที่มืดที่สุด" } },
	sheep = { r = "secret", isl = 2, hint = { en = "A fluffy cloud that walks on grass", th = "ก้อนเมฆปุกปุยที่เดินบนทุ่ง" } },
	sphinx = { r = "secret", isl = 3, hint = { en = "It asks riddles to egg thieves", th = "มันชอบถามคำถามกับขโมยไข่" } },
	wraith = { r = "secret", isl = 4, hint = { en = "A cold spirit that is not quite there", th = "วิญญาณหนาวเย็นที่ไม่มีตัวตน" } },
	shd = { r = "secret", isl = 5, hint = { en = "A dragon forged from the island's shadow", th = "มังกรที่หล่อหลอมจากเงาของเกาะ" } },
	seraph = { r = "divine", isl = "all", hint = { en = "Six wings of holy light", th = "ปีกแสงศักดิ์สิทธิ์หกข้าง" } },
	void = { r = "mystery", isl = "all" },
	sloth = { r = "trash", isl = "all", hint = { en = "Slow... but surprisingly rich", th = "ช้า... แต่รวยผิดปกติ" } },
}
M.cur = "en"
function M.detect()
	local ok, loc = pcall(function() return (LS.RobloxLocaleId or "en-us"):lower() end)
	loc = ok and loc or "en-us"
	for _, code in ipairs({ "th", "es", "pt", "id", "vi", "zh", "ko", "ja" }) do
		if loc:sub(1, 2) == code then return code end
	end
	return "en"
end
function M.set(code)
	if M.L[code] then M.cur = code end
end
function M.tr(key, a, b, c)
	local tbl = M.L[M.cur] or M.L.en
	local t = tbl[key] or M.L.en[key] or key
	if a ~= nil then t = t:gsub("{1}", tostring(a)) end
	if b ~= nil then t = t:gsub("{2}", tostring(b)) end
	if c ~= nil then t = t:gsub("{3}", tostring(c)) end
	return t
end
function M.petName(id)
	local tbl = M.PET_N[M.cur] or M.PET_N.en
	return tbl[id] or M.PET_N.en[id] or id
end
function M.rarName(id)
	local tbl = M.RAR[M.cur] or M.RAR.en
	return tbl[id] or M.RAR.en[id] or id
end
return M
